# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/user.proto\x12\x04user\x1a\x1cgoogle/protobuf/struct.proto\"\x18\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"h\n\x0bListRequest\x12(\n\x07\x66ilters\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\x12\x10\n\x08ordering\x18\x04 \x03(\t\"6\n\rCreateRequest\x12%\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"B\n\rUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"5\n\x0cItemResponse\x12%\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"D\n\x0cListResponse\x12%\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x17.google.protobuf.Struct\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\" \n\x0eResultResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32\x9c\x02\n\x04User\x12\x34\n\tListUsers\x12\x11.user.ListRequest\x1a\x12.user.ListResponse\"\x00\x12\x37\n\nCreateUser\x12\x13.user.CreateRequest\x1a\x12.user.ItemResponse\"\x00\x12\x31\n\x07GetUser\x12\x10.user.GetRequest\x1a\x12.user.ItemResponse\"\x00\x12\x37\n\nUpdateUser\x12\x13.user.UpdateRequest\x1a\x12.user.ItemResponse\"\x00\x12\x39\n\nDeleteUser\x12\x13.user.DeleteRequest\x1a\x14.user.ResultResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETREQUEST._serialized_start=57
  _GETREQUEST._serialized_end=81
  _LISTREQUEST._serialized_start=83
  _LISTREQUEST._serialized_end=187
  _CREATEREQUEST._serialized_start=189
  _CREATEREQUEST._serialized_end=243
  _UPDATEREQUEST._serialized_start=245
  _UPDATEREQUEST._serialized_end=311
  _DELETEREQUEST._serialized_start=313
  _DELETEREQUEST._serialized_end=340
  _ITEMRESPONSE._serialized_start=342
  _ITEMRESPONSE._serialized_end=395
  _LISTRESPONSE._serialized_start=397
  _LISTRESPONSE._serialized_end=465
  _RESULTRESPONSE._serialized_start=467
  _RESULTRESPONSE._serialized_end=499
  _USER._serialized_start=502
  _USER._serialized_end=786
# @@protoc_insertion_point(module_scope)
